image: docker:18

stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_IMAGE_BACKEND: registry.gitlab.com/montogeek/testdoc/backend
  CONTAINER_IMAGE_FRONTEND: registry.gitlab.com/montogeek/testdoc/frontend
  CONTAINER_IMAGE_NGINX: registry.gitlab.com/montogeek/testdoc/nginx
  CONTAINER_IMAGE_DB: registry.gitlab.com/montogeek/testdoc/db
  DOCKER_MACHINE_NAME: proyecto-grado
  NETWORK_NAME: app-network

services:
   - docker:18-dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE_BACKEND:latest || true
    - docker pull $CONTAINER_IMAGE_FRONTEND:latest || true
    - docker pull $CONTAINER_IMAGE_NGINX:latest || true
    - cd code
    - docker build --cache-from $CONTAINER_IMAGE_BACKEND:latest --tag $CONTAINER_IMAGE_BACKEND:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE_BACKEND:latest -f ./production.Dockerfile .
    - docker build --cache-from $CONTAINER_IMAGE_NGINX:latest --tag $CONTAINER_IMAGE_NGINX:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE_NGINX:latest -f ./nginx/production.Dockerfile .
    - docker push $CONTAINER_IMAGE_BACKEND:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE_BACKEND:latest
    - docker push $CONTAINER_IMAGE_NGINX:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE_NGINX:latest
    - cd ../client
    - docker build --cache-from $CONTAINER_IMAGE_FRONTEND:latest --tag $CONTAINER_IMAGE_FRONTEND:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE_FRONTEND:latest -f ./production.Dockerfile .
    - docker push $CONTAINER_IMAGE_FRONTEND:$CI_COMMIT_SHA
    - docker push $CONTAINER_IMAGE_FRONTEND:latest
  only:
    - master
