stages:
  - build_image

variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2
   CONTAINER_IMAGE_BACKEND: registry.gitlab.com/montogeek/testdoc/backend

services:
  - docker:18.09-dind


before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_image:
  stage: build_image
  image: docker:18.09
  script:
    - docker pull $CONTAINER_IMAGE_BACKEND:latest || true
