image: docker:18.09.8

stages:
  - build_image
  - deploy

variables:
  CONTAINER_IMAGE_BACKEND: registry.gitlab.com/montogeek/testdoc/backend
  CONTAINER_IMAGE_FRONTEND: registry.gitlab.com/montogeek/testdoc/frontend
  CONTAINER_IMAGE_NGINX: registry.gitlab.com/montogeek/testdoc/nginx
  CONTAINER_IMAGE_DB: registry.gitlab.com/montogeek/testdoc/db
  DOCKER_MACHINE_NAME: proyecto-grado
  NETWORK_NAME: app-network
  DOCKER_TLS_CERTDIR: ""

services:
   - docker:18.09.8-dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY