stages:
  - build_image

variables:
   DOCKER_HOST: tcp://docker:2375
   DOCKER_DRIVER: overlay2
   # Required to be able to connect to the docker daemon. See https://gitlab.com/gitlab-org/gitlab-runner/issues/4501
   DOCKER_TLS_CERTDIR: ""
   CONTAINER_IMAGE_BACKEND: registry.gitlab.com/montogeek/testdoc/backend

services:
  - docker:stable-dind


before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_image:
  stage: build_image
  script:
    - docker pull $CONTAINER_IMAGE_BACKEND:latest || true
