image: lorisleiva/laravel-docker:latest

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

# Replace the last line with the following lines if you'd rather
# leave StrictHostKeyChecking enabled (replace yourdomain.com):
#
#  ssh-keyscan yourdomain.com >> ~/.ssh/known_hosts
#  chmod 644 ~/.ssh/known_hosts

.change_file_permissions: &change_file_permissions |
  find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;    
  find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;

composer:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - code/vendor/
  script:
    - cd code
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - mv .env.production .env
    - rm .env.test
    - ls -alh
    - php artisan key:generate
  artifacts:
    expire_in: 1 month
    paths:
      - code/vendor/
      - code/.env

npm:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - client/node_modules/
  script:
    - cd client
    - npm install
    - GENERATE_SOURCEMAP=false node --max-old-space-size=4000 ./node_modules/.bin/react-scripts build
  artifacts:
    expire_in: 1 month
    paths:
      - client/build/

production:
  stage: deploy
  script:
    - ls -alh client/build/
    - cd code
    - *init_ssh
    - *change_file_permissions
    - mv .env.production .env
    - rm .env.test
    # - cd ..
    # - ls -alh /var/www/client/
    # - cp -R client/build/ /var/www/client/
    # - ls -alh /var/www/client/
    # - cd code
    - php artisan deploy 68.183.52.252 -s upload -v
    # - chmod -R 755 /var/www/
    # - LATEST_DEPLOY=$(ls -td -- */ | head -n 1)
    # - chmod -R 777 /var/www/${LATEST_DEPLOY}storage/*
    
  environment:
    name: production
    url: http://68.183.52.252
  only:
    - master
