version: "3"

services:
  frontend_production:
    build:
      context: ./client
      dockerfile: production.Dockerfile
    env_file:
      - ./client/.env.${ENV}
    depends_on:
      - backend_production
      - db_production
    container_name: frontend_production
    ports:
      - "80:80"
    networks:
      - app-network_production
  backend_production:
    build:
      context: ./code
      dockerfile: production.Dockerfile
    container_name: backend_production
    env_file:
      - ./code/.env.${ENV}
    depends_on:
      - db_production
    networks:
      - app-network_production
  nginx_production:
    build:
      context: ./code
      dockerfile: ./nginx/production.Dockerfile
    container_name: nginx_production
    ports:
      - "8000:8000"
      - "443:443"
    depends_on:
      - frontend_production
    networks:
      - app-network_production
  db_production:
    image: mysql:5.7.22
    container_name: db_production
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: events
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata_production:/var/lib/mysql
    networks:
      - app-network_production

networks:
  app-network_production:
    driver: bridge

volumes:
  dbdata_production:
    driver: local