version: "3"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env.local
    depends_on:
      - backend
      - nginx
      - db
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./client:/usr/src/app
  backend:
    build:
      context: ./code
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./code:/var/www
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./code:/var/www
      - ./code/nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:5.7.22
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: events
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local