export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_FAILURE = "GET_USER_FAILURE"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"

export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST"
export const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE"
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const REFRESH_TOKEN_REQUEST = "REFRESH_TOKEN_REQUEST"
export const REFRESH_TOKEN_FAILURE = "REFRESH_TOKEN_FAILURE"
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS"

export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST"
export const CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE"
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS"

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST"
export const UPDATE_EVENT_FAILURE = "UPDATE_EVENT_FAILURE"
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS"

export const UPDATE_ASSISTANT_REQUEST = "UPDATE_ASSISTANT_REQUEST"
export const UPDATE_ASSISTANT_SUCCESS = "UPDATE_ASSISTANT_SUCCESS"
export const UPDATE_ASSISTANT_FAILURE = "UPDATE_ASSISTANT_FAILURE"

export const REMOVE_ASSISTANT_REQUEST = "REMOVE_ASSISTANT_REQUEST"
export const REMOVE_ASSISTANT_SUCCESS = "REMOVE_ASSISTANT_SUCCESS"
export const REMOVE_ASSISTANT_FAILURE = "REMOVE_ASSISTANT_FAILURE"

export const ADD_ASSISTANT_REQUEST = "ADD_ASSISTANT_REQUEST"
export const ADD_ASSISTANT_SUCCESS = "ADD_ASSISTANT_SUCCESS"
export const ADD_ASSISTANT_FAILURE = "ADD_ASSISTANT_FAILURE"

export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST"
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE"

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST"
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE"

export const REMOVE_ITEM_REQUEST = "REMOVE_ITEM_REQUEST"
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS"
export const REMOVE_ITEM_FAILURE = "REMOVE_ITEM_FAILURE"

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST"
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILED"

export const MOVE_PIECE = "MOVE_PIECE"
